version: '3'

services:
  intro:
    image: docker/getting-started
    ports:
      - 80:80

  intro-app:
    image: localhost:5000/intro-app:0.0.1
    depends_on:
      - mysql
    networks:
      - db-net
    # Remove build context to use local registry to get the image.
    # build:
    #  context: app
    #  dockerfile: Dockerfile
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: example
      MYSQL_DB: todos
    volumes:
      # Persisting in volume
      # - todo-db:/etc/todos/
      - ./todo-db:/etc/todos/
      - ./app:/app
    entrypoint: sh -c "yarn install && yarn run dev"
    ports:
      - 8080:3000

  mysql:
    image: mysql:5.7
    networks:
      - db-net
    volumes:
      - mysql-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: todos

  registry:
    image: registry:2
    ports:
      - 5000:5000
    volumes:
      - registry-data:/var/lib/registry

networks:
  db-net: { }

volumes:
  # Persisting in volume
  #   todo-db: { }
  mysql-db: { }
  registry-data: { }