version: '3'

services:
  intro:
    image: docker/getting-started
    ports:
      - 80:80

  intro-app:
    image: localhost:5000/intro-app:0.0.1
    build:
      context: app
      dockerfile: Dockerfile
    volumes:
      # Persisting in volume
      # - todo-db:/etc/todos/
      - ./todo-db:/etc/todos/
      - ./app:/app
    entrypoint: sh -c "yarn install && yarn run dev"
    ports:
      - 8080:3000

  registry:
    image: registry:2
    ports:
      - 5000:5000


# Persisting in volume
# volumes:
#   todo-db: { }