version: '3'

services:
  intro:
    image: docker/getting-started
    ports:
      - 80:80

  intro-app:
    image: intro-app:latest
    build:
      context: app
      dockerfile: Dockerfile
    ports:
      - 8080:3000